### ISSUE TITLE
DoesNotExist exception at /search

### ISSUE THREAD

**Issue by aegis2501** [Technikradio/C3FOCSite#17]
## Behaviour mismatch
DoesNotExist exception when attempting to search to nonexistent article
## How to reproduce the bug
Type a search into the search bar that does not yield any query results.
## My environment
Does not apply here.

**Comment by Doralitze** [comment]
This issue seams to be fixed with commit 9888181fac115cd98c6aeb4f66786ecbd975bcc8. Please confirm.

**Comment by aegis2501** [comment]
Sorry for the late answer....can confirm the issue is fixed.
